# Generated by Django 4.2 on 2023-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=1000),
        ),
    ]
