# Generated by Django 4.1.7 on 2023-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default=2, upload_to="image/"),
            preserve_default=False,
        ),
    ]
