# Generated by Django 4.2 on 2023-06-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0003_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
